version: "3.7"
services:
  app:
    image: zayuh/heo:lasted
    user: "1003:983"
    ports:
      - "10002:10002"
    restart: always
    build: .
    links:
      - redis
      - mongodb

  redis:
    image: redis:5-alpine
    user: "1003:983"
    ports:
      - "10003:6379"
    command: ["--requirepass", "Duan2ti!"]
    volumes:
      - "~/data/.docker/data/redis:/data"
      - "~/data/.docker/config/redis/redis.conf:/usr/local/etc/redis/redis.conf"
    restart: always

  mongodb:
    image: mongo:4.2
    user: "1003:983"
    environment:
      MONGO_INITDB_ROOT_USERNAME: heo
      MONGO_INITDB_ROOT_PASSWORD: Duan2ti!
    command: ["--bind_ip", "0.0.0.0"]
    ports:
      - "10004:27017"
    volumes:
      - "~/data/.docker/data/mongodb:/data/db"
    restart: always
